### ISSUE TITLE
Not work with Elastic 1.7.3

### ISSUE THREAD

**Issue by beho1der** [gen1us2k/ariadna#34]
When start update data to base,i get error:
**Failed to create Elastic search client with error no Elasticsearch node available**

I start with this parametr: `./ariadna --es_pg_conn_url "host=localhost user=geo password=geo dbname=geo sslmode=disable" --es_url "http://localhost:9200" --filename "russia-latest.osm.pbf" --download_url "http://download.geofabrik.de/russia-latest.osm.pbf" update`

elasticsearch 1.7.3 work on http://localhost:9200
test elasticsearch : curl -X POST 'http://localhost:9200/tutorial/helloworld/2' -d '{ "message": "Hello World!" }'
{"_index":"tutorial","_type":"helloworld","_id":"2","_version":1,"created":true}

**Comment by gen1us2k** [comment]
This can be because Ariadna's ES module is outdated and it's incompatible with your version of elasticsearch.
Project now is abandoned and I  hope I'll come back to development  in August. Project needs refactoring and also I need to add processing of huge osm.pbf files. I think ariadna can't handle whole Russia country for this case. I made this tool to search intersections and some POIs for Bishkek city. Unfortunately search quality for Russia will be poor and I recommend to use https://pelias.io/ or Nominatim

**Comment by beho1der** [comment]
Many thanks for the answer, I hope that the project will develop, the implementation is very good.
